global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "codevault-backend"
    static_configs:
      - targets: ["host.docker.internal:3000"]
  
  - job_name: 'rabbitmq'
    metrics_path: '/metrics/per-object'
    static_configs:
      - targets: ['rabbitmq:15692']