import "dotenv/config";
import amqp from "amqplib";
import connectDB from "../db/connect.js";
import { Octokit } from "@octokit/rest";
import User from "../models/user.js";
import submission from "../models/submission.js";
import { decryptToken } from "../utils/encryption.js";
import { RETRY_DELAYS_MS, WORK_QUEUES, assertQueueTopology, getRetryQueueName } from "../utils/rabbitmq.js";

const REPO_NAME = "leetcode-sync";
const MAX_RETRY_ATTEMPTS = RETRY_DELAYS_MS.length;

const EXTENSION_MAP = {
    "cpp": "cpp",
    "java": "java",
    "python": "py",
    "python3": "py",
    "javascript": "js",
    "typescript": "ts",
    "csharp": "cs",
    "c": "c",
    "golang": "go",
    "kotlin": "kt",
    "swift": "swift",
    "rust": "rs",
    "ruby": "rb",
    "php": "php",
    "dart": "dart",
    "scala": "scala",
    "elixir": "ex",
    "erlang": "erl",
    "racket": "rkt"
};

const pushFileToGitHub = async (octokit, owner, path, message, content) => {
    let fileSha = undefined;
    try {
        const { data } = await octokit.repos.getContent({ owner, repo: REPO_NAME, path });
        fileSha = data.sha;
    } catch (error) {
        if (error.status !== 404) throw error; 
    }

    await octokit.repos.createOrUpdateFileContents({
        owner,
        repo: REPO_NAME,
        path,
        message,
        content: Buffer.from(content).toString("base64"),
        sha: fileSha,
    });
};

const processJob = async (jobData) => {
    const {submissionId, userId, problemTitle, code, stats, problemDetails} = jobData;

    console.log("\nProcessing job for submission:", submissionId);

    try {
        const user = await User.findById(userId);
        if(!user || !user.accessToken){
            throw new Error("User not found or missing access token");
        }

        const plainTextToken = decryptToken(user.accessToken);
        const octokit = new Octokit({auth: plainTextToken});
        const owner = user.username;

        try {
            await octokit.repos.get({owner, repo: REPO_NAME});
        } catch(err) {
            if(err.status === 404){
                await octokit.repos.createForAuthenticatedUser({
                    name: REPO_NAME,
                    description: "Auto-synced LeetCode solutions via CodeVault",
                    private: true,
                    auto_init: true
                });
            } else {
                throw err;
            }
        }

        const folderName = problemTitle.replace(/[^a-zA-Z0-9 -]/g, "").replace(/\s+/g, "_");
        const fileExtension = EXTENSION_MAP[stats.lang] || "txt";
        const solutionPath = `${folderName}/solution.${fileExtension}`;

        const difficultyColor = problemDetails?.difficulty === "Easy" ? "🟩" : problemDetails?.difficulty === "Medium" ? "🟨" : "🟥";
        const tags = problemDetails?.topicTags?.map(tag => `\`${tag.name}\``).join(" ") || "";

        const readmeContent = `
# ${problemTitle}
        
${difficultyColor} **Difficulty:** ${problemDetails?.difficulty || "Unknown"}
        
🏷️ **Topics:** ${tags}

---

## Problem Description
${problemDetails?.content || "Description not available."}

---
        
*Auto-generated by [CodeVault](https://github.com/kartik-py12/CodeVault)*
`;

        const readmePath = `${folderName}/README.md`;
        console.log(`Pushing README.md to ${readmePath}...`);
        await pushFileToGitHub(octokit, owner, readmePath, `Docs: Add README for ${problemTitle}`, readmeContent);

        const commitMessage = `CodeVault Sync: ${problemTitle} | Runtime: ${stats.status_runtime || stats.runtime} | Memory: ${stats.status_memory || stats.memory}`;
        
        console.log(`Pushing Solution to ${solutionPath}...`);
        await pushFileToGitHub(octokit, owner, solutionPath, commitMessage, code);

        console.log(`Successfully synced submission ${submissionId} to GitHub repository ${REPO_NAME}`);

        await submission.findByIdAndUpdate(submissionId, {status: "COMPLETED"});

        return { success: true, retryable: false };
    } catch (error) {
        console.error(`❌ Error processing job for ${problemTitle}:`, error.message);
        const isPermanentError = /User not found or missing access token/i.test(error.message);
        return { success: false, retryable: !isPermanentError };
    }
}

const startWorker = async () => {
    await connectDB();

    try {
        const connection = await amqp.connect(process.env.RABBITMQ_URI);
        const channel = await connection.createChannel();
        
        const queue = WORK_QUEUES.GITHUB_SYNC;
        await assertQueueTopology(channel);
        
        channel.prefetch(1);
        
        console.log("GitHub Worker is waiting for messages in queue:", queue);
        
        channel.consume(queue, async (msg) => {
            if(msg !== null){
                const jobData = JSON.parse(msg.content.toString());
                const { success, retryable } = await processJob(jobData);
                const currentRetryCount = Number(msg.properties?.headers?.["x-retry-count"] || 0);
                const nextRetryCount = currentRetryCount + 1;
                
                if(success){
                    channel.ack(msg);
                } else {
                    if (retryable && nextRetryCount <= MAX_RETRY_ATTEMPTS) {
                        channel.sendToQueue(getRetryQueueName(queue, nextRetryCount), Buffer.from(JSON.stringify(jobData)), {
                            persistent: true,
                            headers: {
                                ...(msg.properties?.headers || {}),
                                "x-retry-count": nextRetryCount
                            }
                        });
                        console.warn(`Retrying GitHub job ${jobData.submissionId}. Attempt ${nextRetryCount}/${MAX_RETRY_ATTEMPTS}`);
                        channel.ack(msg);
                    } else {
                        await submission.findByIdAndUpdate(jobData.submissionId, {status: "FAILED"});
                        channel.nack(msg, false, false);
                    }
                }
            }
        });
    } catch (error) {
        console.error("Error starting GitHub Worker:", error.message);
    }
};

startWorker();